/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    home: []
    blocks: []
    legal: []
    style: []
    'tab-one': []
    'tab-two': []
    'tab-three': []
    dashboard: []
    'profile.edit': []
    'profile.update': []
    'profile.destroy': []
    'password.edit': []
    'password.update': []
    appearance: []
    register: []
    login: []
    'password.request': []
    'password.email': []
    'password.reset': [
      {
        name: 'token'
        required: true
      }
    ]
    'password.store': []
    'verification.notice': []
    'verification.verify': [
      {
        name: 'id'
        required: true
      },
      {
        name: 'hash'
        required: true
      }
    ]
    'verification.send': []
    'password.confirm': []
    logout: []
    source: [
      {
        name: 'path'
        required: true
      }
    ]
    'component-source': [
      {
        name: 'path'
        required: true
      }
    ]
    md: [
      {
        name: 'path'
        required: true
      }
    ]
    docs: [
      {
        name: 'path'
        required: true
      }
    ]
    demo: [
      {
        name: 'path'
        required: true
      }
    ]
    'storage.local': [
      {
        name: 'path'
        required: true
      }
    ]
  }
}
export {}
